### ISSUE TITLE
Come to Trento

### ISSUE THREAD

**Issue by gdaddato1** [icosac/ros2-pub-sub-eg#3]
We want you **here**.

**Comment by pla10** [comment]
Muahaha.. let me work on this

**Comment by pla10** [comment]
come faceva a far apparire il messaggio qui nella issue del push nel branch? @gdaddato1 @icosac

**Comment by icosac** [comment]
Non ho ben capito. Potresti spiegare meglio i requisiti da te richiesti per questa issue?

**Comment by icosac** [comment]
#2

**Comment by pla10** [comment]
<img width="878" alt="image" src="https://github.com/user-attachments/assets/10f5e8b6-5c54-4869-a75b-181677c35d4b">
Like in the screenshot attached

**Comment by pla10** [comment]
ok understood

**Comment by pla10** [comment]
Yeeeee

**Comment by pla10** [comment]
In the commit I have added the solution to this issue..
Check out the GIF

**Comment by gdaddato1** [comment]
We cannot open it

**Comment by gdaddato1** [comment]
ok, visto!
